#!/bin/sh

# host-connect-setup.sh
#
# Generates the guest-side SSH connection assets. Runs on the *host*, because
# only the host knows its own login name and SSH host key.
#
# Writes into <output-dir>:
#
#   host-proxy-ssh.sh      the connection script host-proxy invokes in the guest
#   ssh/known_hosts        this host's public host key, pinned under a stable alias
#   ssh/host-wrapper.env   host-provided values consumed by the connection script
#
# The guest resolves the host address from its own default route at connection
# time, because the container gateway address is not stable: on macOS native
# containers it depends on the networks configured for the system, so any
# hardcoded value is a guess that breaks on the next machine.
#
# A moving address is only safe if host identity is verified independently of
# it. The host key is therefore pinned under a fixed alias (HostKeyAlias), which
# lets the connection use StrictHostKeyChecking=yes even though the address it
# connects to may differ from run to run.
#
# Usage:
#   sh host-connect-setup.sh <output-dir> [options]
#
# Options:
#   --key NAME        private key filename inside <output-dir>/ssh
#                     (default: id_ed25519)
#   --user NAME       host login user (default: $USER)
#   --alias NAME      host key alias used for verification (default: host-wrapper)
#   --gateway ADDR    pin the host address instead of detecting it in the guest;
#                     use for guests whose default route is not the host, such
#                     as Docker Desktop (--gateway host.docker.internal)
#   --host-key FILE   host public key to pin (default: first readable of
#                     /etc/ssh/ssh_host_{ed25519,ecdsa,rsa}_key.pub)

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

OUT_DIR=""
KEY_NAME="id_ed25519"
HOST_USER="${USER:-$(id -un)}"
KEY_ALIAS="host-wrapper"
GATEWAY=""
HOST_KEY_FILE=""

usage() {
    sed -n '3,40p' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-1}"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --key)      KEY_NAME="$2"; shift 2 ;;
        --user)     HOST_USER="$2"; shift 2 ;;
        --alias)    KEY_ALIAS="$2"; shift 2 ;;
        --gateway)  GATEWAY="$2"; shift 2 ;;
        --host-key) HOST_KEY_FILE="$2"; shift 2 ;;
        -h|--help)  usage 0 ;;
        -*)         echo "host-connect-setup: unknown option '$1'" >&2; usage 1 ;;
        *)
            if [ -n "$OUT_DIR" ]; then
                echo "host-connect-setup: unexpected argument '$1'" >&2
                usage 1
            fi
            OUT_DIR="$1"; shift ;;
    esac
done

if [ -z "$OUT_DIR" ]; then
    echo "host-connect-setup: missing <output-dir>" >&2
    usage 1
fi

# Locate a host public key to pin.
if [ -z "$HOST_KEY_FILE" ]; then
    for candidate in \
        /etc/ssh/ssh_host_ed25519_key.pub \
        /etc/ssh/ssh_host_ecdsa_key.pub \
        /etc/ssh/ssh_host_rsa_key.pub
    do
        if [ -r "$candidate" ]; then
            HOST_KEY_FILE="$candidate"
            break
        fi
    done
fi

if [ -z "$HOST_KEY_FILE" ] || [ ! -r "$HOST_KEY_FILE" ]; then
    echo "host-connect-setup: no readable SSH host public key found." >&2
    echo "  Looked in /etc/ssh. Is sshd installed and enabled on this host?" >&2
    echo "  Pass --host-key FILE to point at one explicitly." >&2
    exit 1
fi

# The connection script is a file kept beside this one rather than something
# generated here: it is identical on every host, because everything that varies
# lives in ssh/host-wrapper.env. Check it before writing anything, so a failure
# here leaves no half-written bundle behind.
CONNECT_SOURCE="$SCRIPT_DIR/share/host-proxy-ssh.sh"
if [ ! -r "$CONNECT_SOURCE" ]; then
    echo "host-connect-setup: cannot read $CONNECT_SOURCE." >&2
    echo "  The connection script ships alongside this one; run both from a" >&2
    echo "  checkout rather than copying this file out on its own." >&2
    exit 1
fi

mkdir -p "$OUT_DIR/ssh"

# 1. Pin the host key under a stable alias.
#    Only the type and the key material are kept; the trailing comment is not
#    part of the identity and only adds noise to the pin.
KNOWN_HOSTS="$OUT_DIR/ssh/known_hosts"
printf '# Host identity for host-wrapper, pinned under the alias "%s".\n' "$KEY_ALIAS" > "$KNOWN_HOSTS"
printf '# Regenerate with host-connect-setup.sh if the host key changes.\n' >> "$KNOWN_HOSTS"
printf '%s %s\n' "$KEY_ALIAS" "$(cut -d' ' -f1,2 "$HOST_KEY_FILE")" >> "$KNOWN_HOSTS"
chmod 644 "$KNOWN_HOSTS"

# Fail here rather than in the guest if the pin is malformed.
if ! ssh-keygen -lf "$KNOWN_HOSTS" >/dev/null 2>&1; then
    echo "host-connect-setup: generated known_hosts is not a valid entry:" >&2
    cat "$KNOWN_HOSTS" >&2
    exit 1
fi

# 2. Record the host-provided values.
shquote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

ENV_FILE="$OUT_DIR/ssh/host-wrapper.env"
{
    echo "# Generated by host-connect-setup.sh -- values supplied by the host."
    echo "# Edit this file rather than host-proxy-ssh.sh."
    echo "HOST_USER=$(shquote "$HOST_USER")"
    echo "HOST_KEY=$(shquote "./ssh/$KEY_NAME")"
    echo "HOST_KEY_ALIAS=$(shquote "$KEY_ALIAS")"
    if [ -n "$GATEWAY" ]; then
        echo "# Address pinned at provisioning time; guest detection is skipped."
        echo "HOST_GATEWAY=$(shquote "$GATEWAY")"
    else
        echo "# Leave unset to detect the host address from the guest default route."
        echo "# Set it for guests whose default route is not the host, for example:"
        echo "#HOST_GATEWAY='host.docker.internal'"
    fi
} > "$ENV_FILE"
chmod 644 "$ENV_FILE"

# 3. Install the connection script, checked for readability above.
CONNECT_SCRIPT="$OUT_DIR/host-proxy-ssh.sh"
cp "$CONNECT_SOURCE" "$CONNECT_SCRIPT"
chmod +x "$CONNECT_SCRIPT"

echo "[*] Wrote $CONNECT_SCRIPT"
echo "[*] Wrote $KNOWN_HOSTS (host key pinned as '$KEY_ALIAS')"
echo "[*] Wrote $ENV_FILE (HOST_USER=$HOST_USER, key ./ssh/$KEY_NAME)"
